language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - 0.6
  - nightly

notifications:
  email: false

git:
  depth: 3

after_success:
  - [[ $TRAVIS_JULIA_VERSION = 0.5 && $TRAVIS_OS_NAME = linux ]] && DO_AFTER = 1
  - [[ DO_AFTER = 1 ]] && julia -e 'Pkg.add("Documenter")'
  - [[ DO_AFTER = 1 ]] && julia -e 'cd(Pkg.dir("OpenEphysLoader")); include(joinpath("docs", "make.jl"))'
  - [[ DO_AFTER = 1 ]] && julia -e 'cd(Pkg.dir("OpenEphysLoader")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
